# Generated by Django 5.0.3 on 2024-04-03 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_api', '0002_ticket_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlines_api.airplane'),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.FloatField(),
        ),
    ]
