# Generated by Django 5.0.3 on 2024-04-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_api', '0003_alter_flight_airplane_alter_route_distance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat')},
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'row', 'seat')},
        ),
    ]
