# Generated by Django 5.0.3 on 2024-04-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_api', '0005_airplane_image_crew_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time']},
        ),
        migrations.AddField(
            model_name='airplane',
            name='speed_per_hour',
            field=models.IntegerField(default=900),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
