# Generated by Django 5.0.3 on 2024-04-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_api', '0006_alter_flight_options_airplane_speed_per_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='speed_per_hour',
        ),
    ]
