# Generated by Django 5.0.3 on 2025-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_api', '0009_order_is_cancelled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='flight',
            name='crews',
            field=models.ManyToManyField(blank=True, related_name='flights', to='airlines_api.crew'),
        ),
    ]
